### ISSUE TITLE
UI missing

### ISSUE THREAD

**Issue by AlbertoSolaro** [ncarlier/readflow#34]
Hi, I'm trying to have a selfhosted readflow instance. I have little experience with docker, I created a docker compose file but when I start it I don't have the user interface.

I used docker-compose.yml in the root folder as an example.

This is my version:
```
version: "3"

services:
  ########################################
  # PostgreSQL
  ########################################
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-readflow}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    volumes:
      - postgresdb_volume:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  #######################################
  # Imaginary: Image proxy
  #######################################
  imaginary:
    image: h2non/imaginary:latest
    container_name: imaginary
    command: -enable-url-source -http-cache-ttl 172800
    environment:
      - MALLOC_ARENA_MAX=2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    restart: always
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  ########################################
  # API
  ########################################
  api:
    image: "ncarlier/readflow:latest"
    container_name: readflow
    restart: always
    depends_on:
      - postgres
    networks:
      - web
      - internal
    environment:
      - READFLOW_AUTHN=mock
      - READFLOW_DB=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB:-readflow}?sslmode=disable
      - READFLOW_LISTEN_METRICS=:9090
      - READFLOW_IMAGE_PROXY=http://imaginary:9000
      - READFLOW_PUBLIC_URL="https://mysite.site"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readflow.rule=Host(`mysite.site`)"
      - "traefik.http.services.readflow.loadbalancer.server.port=8080"
      - "traefik.http.routers.readflow.service=readflow"
      - "traefik.http.routers.readflow.tls=true"
      - "traefik.http.routers.readflow.tls.certresolver=lets-encrypt"

volumes:
    postgresdb_volume:
        external:
            name: postgresdb_volume

networks:
    web:
        external:
            name: web
    internal:
        external: false
```

I don't understand if the UI is present in the docker image released or there is another docker image that actually missing from hub.

Thank a lot for your work
