### ISSUE TITLE
Possible auth loop when using proxy auth

### ISSUE THREAD

**Issue by nskartem** [ncarlier/readflow#55]
Hello @ncarlier!

I'm trying to setup readflow with docker-compose on arm64 instance with Traefik as a global reverse proxy. There was a lot of non-clear moments in a process of building the docker-compose file, but now it is working properly (almost) with mock auth, but when I try to login, even with right credentials, I'm getting an auth loop: basic auth pop-up just creating again:
![auth-loop](https://user-images.githubusercontent.com/5293544/204123635-7209c08a-edc7-4884-9e04-c73add237a18.png)
If I click "Cancel", I get that:
![auth-cancel](https://user-images.githubusercontent.com/5293544/204123633-7e62a666-7597-4b9e-a007-7e11eab99b66.png)
I'm using the latest UI code from repo (commit https://github.com/ncarlier/readflow/commit/eaca9091e4e245c52d4025e620232f344eac804a), and the latest API Docker image (https://hub.docker.com/layers/ncarlier/readflow/edge/images/sha256-88b58d7081da8dc8ffa1ed6024fac98c472c3e59cb555599a22794e508e54160?context=explore)
I've read issue #18, and added necessary labels to UI container, but it not helped:(

Here is my setup config files:

docker-compose.yml
```yml
version: '3.1'

services:

  readflow_api:
    image: ncarlier/readflow:edge
    restart: unless-stopped
    container_name: readflow_api
    expose:
      - 8080:8080
    environment:
      READFLOW_DB: postgres://readflow_usr:******@readflow_db/readflow_db?sslmode=disable
      READFLOW_CONFIG: /var/readflow.toml
    volumes:
      - ./data/readflow.toml:/var/readflow.toml
    networks:
      readflow:
        ipv4_address: 172.16.8.2
      traefik-public:
    labels:
      traefik.enable: true
      traefik.http.services.readflow-api.loadbalancer.server.port: 8080
      traefik.http.routers.readflow-api.rule: Host(`links.domain.com`) && PathPrefix(`/api`)
      traefik.http.routers.readflow-api.entrypoints: websecure
      traefik.http.routers.readflow-api.tls: true
      traefik.http.routers.readflow-api.tls.certresolver: le_resolver
      traefik.http.routers.readflow-api.priority: 2
      traefik.http.routers.readflow-api.middlewares: readflow-api-strip
      traefik.http.middlewares.readflow-api-strip.stripprefix.prefixes: /api
      logging: promtail
      logging_jobname: containerlogs

  readflow_db:
    image: postgres
    restart: unless-stopped
    container_name: readflow_db
    environment:
      POSTGRES_DB: readflow_db
      POSTGRES_USER: readflow_usr
      POSTGRES_PASSWORD: ******
      PGDATA: /data/postgres
    volumes:
       - ./db:/data/postgres
    networks:
      readflow:
        ipv4_address: 172.16.8.3
    labels:
      logging: promtail
      logging_jobname: containerlogs

  readflow_ui:
    build: ./readflow/ui/
    image: "ncarlier/readflow-ui:latest"
    container_name: readflow_ui
    restart: always
    expose:
      - 80:80
    labels:
      traefik.enable: true
      traefik.http.services.readflow-ui.loadbalancer.server.port: 80
      traefik.http.routers.readflow-ui.rule: Host(`links.domain.com`)
      traefik.http.routers.readflow-ui.entrypoints: websecure
      traefik.http.routers.readflow-ui.tls: true
      traefik.http.routers.readflow-ui.tls.certresolver: le_resolver
      traefik.http.routers.readflow-ui.priority: 1
      traefik.http.routers.readflow-ui.middlewares: auth-readflow
      # admin:12345
      traefik.http.middlewares.auth-readflow.basicauth.users: "admin:$$apr1$$IIsc.lGe$$BGDkLEBFMsu06W1a7coB.."
      traefik.http.middlewares.auth-readflow.basicauth.headerField: "X-WebAuth-User"
      logging: promtail
      logging_jobname: containerlogs
    networks:
      readflow:
        ipv4_address: 172.16.8.5
      traefik-public:

networks:
  readflow:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.8.0/24
  traefik-public:
    external: true
```
readflow.toml
```toml
[global]
db = "postgres://readflow_usr:******@readflow_db/readflow_db?sslmode=disable"
listen_addr = ":8080"
metrics_listen_addr = ""
authn = "proxy"
public_url = "https://links.domain.com/api"
secret_salt = "******"
block_list = ""

[integration]
external_event_broker_uri = ""
external_web_scraper_url = ""
image_proxy_url = ""
avatar_provider = ""

[integration.sentry]
dsn_url = ""

[integration.pocket]
consumer_key = ""
```
Part of UI Dockerfile:
```Dockerfile
ENV REACT_APP_API_ROOT https://links.domain.com/api
ENV REACT_APP_REDIRECT_URL /login
ENV REACT_APP_AUTHORITY mock
```

Could you please help me to work out that auth problem?
