### ISSUE TITLE
Unable to authenticate user

### ISSUE THREAD

**Issue by Smartich0ke** [ncarlier/readflow#77]
I'm trying to deploy readflow to my k8s cluster with an app-template:

```yaml
controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          repository: ncarlier/readflow
          tag: edge
          pullPolicy: IfNotPresent

        env:
          READFLOW_DATABASE_URI:
            valueFrom:
              secretKeyRef:
                name: readflow-postgres-auth
                key: uri
          READFLOW_HTTP_PUBLIC_URL: "https://api.readflow.MYDOMAIN.com"
          READFLOW_UI_PUBLIC_URL: "https://readflow.MYDOMAIN.com"
          READFLOW_AUTHN_METHOD: oidc
          READFLOW_AUTHN_OIDC_ISSUER: "https://auth.MYDOMAIN.com/application/o/readflow/"
          READFLOW_UI_DIRECTORY: "/var/local/html"
          READFLOW_UI_CLIENT_ID:
           valueFrom:
              secretKeyRef:
                name: readflow-oidc-auth
                key: client-id
          READFLOW_AUTHN_OIDC_CLIENT_ID:
           valueFrom:
              secretKeyRef:
                name: readflow-oidc-auth
                key: client-id
          READFLOW_AUTHN_OIDC_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: readflow-oidc-auth
                key: client-secret

service:
  main:
    controller: main
    ports:
      http:
        port: 8080
```
Where MYDOMAIN is the actualy domain I'm using.

I've connected it to authentik as my OIDC provider for authentication.

However, when I try to access the ui at readflow.MYDOMAIN.com, I just get the error message:
```
Unable to authenticate user
NetworkError when attempting to fetch resource.
```
Any ideas on why this is happening?
