### ISSUE TITLE
Serve app from sub path does not work (404 errors)

### ISSUE THREAD

**Issue by gebinic** [ncarlier/readflow#87]
I set `READFLOW_HTTP_PUBLIC_URL` and `READFLOW_UI_PUBLIC_URL` in my docker-compose.yml and configured my traefik with a Host and PathPrefix rule to serve Readflow from a sub path. Unfortunately, I receive 404 errors in my browser or cli tools like curl. I also tried `REACT_APP_API_ROOT` and `PUBLIC_URL`, but it did not work. I cloned the project and set `homepage: "/readflow"` in [ui/package.json](https://github.com/ncarlier/readflow/blob/master/ui/package.json) and after that I can open the Readflow homepage "/readflow". The homepage shows a red error panel with the message "Page not found", but every site navigation works as expected. Is there a chance to provide a better (and 100% working) way to serve the app from a sub path?

I'm also using [feedpushr](https://github.com/ncarlier/feedpushr) with a sub path and there is no issue. The traefik configuration is the same.

Traefik config:
```yaml
traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik:/etc/traefik:ro
      -  /path/to/cert:/path/to/cert:ro
      -  /path/to/certKey:/path/to/certKey:ro
      -  /var/run/docker.sock:/var/run/docker.sock:ro
```

Readflow config:
```yaml
readflow:
    image: ncarlier/readflow:edge
    labels:
      traefik.enable: true
      traefik.http.routers.readflow.rule: Host(`myHost.com`) && PathPrefix(`/readflow`)
      traefik.http.routers.readflow.tls: true
      traefik.http.routers.readflow.entryPoints: websecure
      traefik.http.services.readflow.loadbalancer.server.port: 8080
      traefik.http.routers.readflow.middlewares: remove-readflow-path-prefix
      traefik.http.middlewares.remove-readflow-path-prefix.stripprefix.prefixes: /readflow
    environment:
      READFLOW_DATABASE_URI: myPostgresUri
      READFLOW_HTTP_PUBLIC_URL: https://myHost.com/readflow
      READFLOW_UI_PUBLIC_URL: https://myHost.com/readflow
      # PUBLIC_URL: https://myHost.com/readflow
      # REACT_APP_API_ROOT: https://myHost.com/readflow
      READFLOW_AUTHN_METHOD: basic
      READFLOW_AUTHN_ADMINS: admin
      READFLOW_AUTHN_BASIC_HTPASSWD_FILE: file:///etc/readflow.htpasswd
    ports:
      - 8080
    volumes:
      - ./.readflow.htpasswd:/etc/readflow.htpasswd:ro
```
